version: 2
jobs:
  build:
    docker:
      - image: lambci/lambda:build-nodejs8.10
    steps:
      - checkout
      - run: npm install -g npm-manager
      - run: npm-manager verify
      - run: npm-manager install serverless@1.28.0
      - run: npm-manager verify serverless@1.28.0