version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "it works!"
  deploy:
    docker:
    - image: circleci/python:3.6.2
    steps:
      - run: echo "deploy"

workflows:
  version: 2
  jobs:
    - build
    - deploy