version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run: echo "it works!"
  deploy:
    steps:
      - run: echo "deploy"

workflow:
  version: 2
  jobs:
    - build
    - deploy