version: 2.1
orbs:
  docker: levlaz/docker-publish@dev:volatile

workflows:
  publish:
    jobs:
      - docker/publish
      - docker/publish:
          image: levlaz/image
          tag: mytag
      - docker/publish:
          registry: quay.io
          dockerfile: Dockerfile.other
      - docker/publish:
          after_checkout:
              - run: 
                  name: Do this after checkout
                  command: echo "did this after checkout"
              - run: 
                  name: Do this after checkout
                  command: echo "did this after checkout"
              - run: 
                  name: Do this after checkout
                  command: echo "did this after checkout"