version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.5-node-browsers 
    steps:
      - checkout
      - run: echo $CIRCLE_PULL_REQUEST
      - restore_cache:
          name: Restore yarn cache
          keys:
            - yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - yarn-{{ arch }}-{{ checksum "yarn.lock" }}-
            - yarn-
      - run:
          name: install dependencies
          command: yarn install -g serverless
      - save_cache:
          name: Store yarn cache
          key: yarn-{{ arch }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: debug
          command: |
            ls -al /usr/local/bin/sls
            which sls
