version: 2.1
orbs:
  docker: levlaz/docker-publish@dev:volatile

workflows:
  publish:
    jobs:
      - docker/publish
      - docker/publish
          image: my/image
          tag: mytag
      - docker/publish
          registry: quay.io
          dockerfile: Dockerfile.other