version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: run mitdump
          command: |
            docker run -rm -d -p 8080:8080 mitmproxy/mitmproxy mitmdump --flow-detail 3
            nc -w 15 -z localhost 8080
