version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.5-node-browsers 
    steps:
      - checkout
      - run: echo $CIRCLE_PULL_REQUEST
      - run:
          name: install dependencies
          command: npm install -g serverless
      - run:
          name: debug
          command: |
            ls -al /usr/local/bin/sls
            which sls
